
import { EffectItem } from './types';
import { PROMPTS } from './prompts';

export const EFFECTS_DATA: Omit<EffectItem, 'component'>[] = [
  // --- VIETNAM SPECIAL ---
  { id: 'vietnam-flag', title: 'VN. Cờ Đỏ Sao Vàng', description: 'A hyper-realistic simulation of the Vietnamese flag with dynamic cloth physics and golden particle effects.', prompt: 'Create a highly detailed, 60fps canvas simulation of the Vietnamese flag waving in the wind with cloth physics, specular lighting, and golden "glory" particles rising from the bottom.' },
  { id: 'vietnam-drum', title: 'VN. Trống Đồng', description: 'Interactive procedural Dong Son drum patterns with metallic shader effects.', prompt: 'Generate an intricate, procedural bronze drum face (Dong Son culture) using HTML5 Canvas. Implement a metallic shader effect, rotating geometric rings, and mouse-interactive lighting.' },

  // --- SCROLL EFFECTS (1-28) ---
  { id: 'parallax-basic', title: '01. Parallax Basic', description: 'Cinematic depth with smooth transform translations.', prompt: PROMPTS['parallax-basic'] },
  { id: 'parallax-multi', title: '02. Multi-layer Parallax', description: 'Deep space 3D effect with multiple moving planes.', prompt: PROMPTS['parallax-multi'] },
  { id: 'horizontal-scroll', title: '03. Horizontal Scroll', description: 'A sticky horizontal gallery driven by vertical scroll.', prompt: PROMPTS['horizontal-scroll'] },
  { id: 'scroll-trigger', title: '04. Scroll Trigger', description: 'Elements that flow into view with staggered elegance.', prompt: PROMPTS['scroll-trigger'] },
  { id: 'scroll-snap', title: '05. Scroll Snap', description: 'Full-screen immersive sections with snap points.', prompt: PROMPTS['scroll-snap'] },
  { id: 'scroll-progress', title: '06. Scroll Progress', description: 'A minimal, non-intrusive progress visualization.', prompt: PROMPTS['scroll-progress'] },
  { id: 'scroll-reveal', title: '07. Scroll Reveal', description: 'A curtain-wipe effect revealing content underneath.', prompt: PROMPTS['scroll-reveal'] },
  { id: 'scroll-blur', title: '08. Scroll Blur', description: 'Dynamic focus shifting based on scroll position.', prompt: PROMPTS['scroll-blur'] },
  { id: 'scroll-scale', title: '09. Scroll Scale', description: 'A portal effect where the hero shrinks into a card.', prompt: PROMPTS['scroll-scale'] },
  { id: 'scroll-rotation', title: '10. Scroll Rotation', description: 'Elements that rotate and orbit based on scroll velocity.', prompt: PROMPTS['scroll-rotation'] },
  { id: 'scroll-velocity', title: '11. Scroll Velocity', description: 'Typography that skews based on scroll speed.', prompt: PROMPTS['scroll-velocity'] },
  { id: 'scroll-stacking', title: '12. Stacking Cards', description: 'Cards that stick and stack on top of each other.', prompt: PROMPTS['scroll-stacking'] },
  { id: 'scroll-text-fill', title: '13. Text Gradient Fill', description: 'Reading progress visualization within text.', prompt: PROMPTS['scroll-text-fill'] },
  { id: 'scroll-split', title: '14. Split Screen', description: 'Dual panels scrolling in opposite directions.', prompt: PROMPTS['scroll-split'] },
  { id: 'scroll-blend', title: '15. Mix Blend Mode', description: 'High contrast color inversion on scroll.', prompt: PROMPTS['scroll-blend'] },
  { id: 'scroll-line-reveal', title: '16. Line Reveal', description: 'Text lights up line-by-line as you read.', prompt: PROMPTS['scroll-line-reveal'] },
  { id: 'scroll-marquee', title: '17. Scroll Marquee', description: 'Text lines sliding horizontally based on scroll.', prompt: PROMPTS['scroll-marquee'] },
  { id: 'scroll-staggered-fill', title: '18. Staggered Fill', description: 'Lines fill horizontally in sequence as you scroll.', prompt: PROMPTS['scroll-staggered-fill'] },
  { id: 'scroll-video', title: '19. Video Scrub', description: 'Controlling video playback time via scroll.', prompt: PROMPTS['scroll-video'] },
  { id: 'scroll-canvas', title: '20. Canvas Animation', description: 'High-performance canvas particles driven by scroll.', prompt: PROMPTS['scroll-canvas'] },
  { id: 'scroll-hijack', title: '21. Sticky Flow', description: 'A sticky section slider simulating scroll hijacking.', prompt: PROMPTS['scroll-hijack'] },
  { id: 'scroll-infinite', title: '22. Infinite Loop', description: 'Seamless content looping for infinite storytelling.', prompt: PROMPTS['scroll-infinite'] },
  { id: 'scroll-pinning', title: '23. Scroll Pinning', description: 'Split layout with sticky side content.', prompt: PROMPTS['scroll-pinning'] },
  { id: 'scroll-morph', title: '24. Shape Morph', description: 'SVG or border-radius morphing on scroll.', prompt: PROMPTS['scroll-morph'] },
  { id: 'scroll-depth', title: '25. Depth Tunnel', description: 'Fake 3D z-axis flythrough effect.', prompt: PROMPTS['scroll-depth'] },
  { id: 'scroll-distortion', title: '26. Text Distortion', description: 'Liquid turbulence effect on typography.', prompt: PROMPTS['scroll-distortion'] },
  { id: 'scroll-zoom', title: '27. Deep Zoom', description: 'Massive scale zoom revealing hidden details.', prompt: PROMPTS['scroll-zoom'] },
  { id: 'scroll-color', title: '28. Color Shift', description: 'Dynamic background color interpolation.', prompt: PROMPTS['scroll-color'] },

  // --- CURSOR EFFECTS (29-55) ---
  { id: 'cursor-custom', title: '29. Custom Cursor', description: 'Replaced native cursor with styled div elements.', prompt: PROMPTS['cursor-custom'] },
  { id: 'cursor-follower', title: '30. Cursor Follower', description: 'Lagging spring physics follower for fluid motion.', prompt: PROMPTS['cursor-follower'] },
  { id: 'cursor-magnetic', title: '31. Magnetic Cursor', description: 'Buttons that snap to and attract the cursor.', prompt: PROMPTS['cursor-magnetic'] },
  { id: 'cursor-distortion', title: '32. Hover Distortion', description: 'Liquid displacement effects on hover.', prompt: PROMPTS['cursor-distortion'] },
  { id: 'cursor-reveal', title: '33. Image Reveal', description: 'Flashlight mask revealing hidden content.', prompt: PROMPTS['cursor-reveal'] },
  { id: 'cursor-blend', title: '34. Mix Blend', description: 'Inverting colors for high contrast visibility.', prompt: PROMPTS['cursor-blend'] },
  { id: 'cursor-trail', title: '35. Cursor Trail', description: 'Particle system trailing behind movement.', prompt: PROMPTS['cursor-trail'] },
  { id: 'cursor-ripple', title: '36. Click Ripple', description: 'Expanding wave animations on click.', prompt: PROMPTS['cursor-ripple'] },
  { id: 'cursor-scale', title: '37. Context Scaling', description: 'Cursor changes shape based on hovered element.', prompt: PROMPTS['cursor-scale'] },
  { id: 'cursor-tooltip', title: '38. Following Tooltip', description: 'Information tag attached to the mouse.', prompt: PROMPTS['cursor-tooltip'] },
  { id: 'cursor-spotlight', title: '39. CSS Spotlight', description: 'Revealing borders/gradients near mouse.', prompt: PROMPTS['cursor-spotlight'] },
  { id: 'cursor-gravity', title: '40. Gravity Effect', description: 'Elements pulled towards the cursor.', prompt: PROMPTS['cursor-gravity'] },
  { id: 'cursor-tilt', title: '41. 3D Tilt', description: 'Cards rotating to face the mouse position.', prompt: PROMPTS['cursor-tilt'] },
  { id: 'cursor-noise', title: '42. Noise Brush', description: 'Revealing static noise texture on hover.', prompt: PROMPTS['cursor-noise'] },
  { id: 'cursor-morph', title: '43. Morphing Shape', description: 'Cursor deforms based on velocity/direction.', prompt: PROMPTS['cursor-morph'] },
  { id: 'cursor-hover-mask', title: '44. Hover Mask', description: 'Text changes color inside cursor radius.', prompt: 'Create a cursor that acts as a mask, changing the color of text underneath it.' },
  { id: 'cursor-text-replace', title: '45. Text Replacement', description: 'Cursor becomes the word "View" on images.', prompt: 'When hovering an image, the cursor turns into a text label "VIEW".' },
  { id: 'cursor-image-float', title: '46. Floating Image', description: 'Images appearing near cursor on list hover.', prompt: 'Hovering over a list item shows a related image floating next to the cursor.' },
  { id: 'cursor-blend-text', title: '47. Difference Blend', description: 'Text colors invert under the cursor.', prompt: 'Use mix-blend-mode difference on the cursor to invert text colors.' },
  { id: 'cursor-circle-expand', title: '48. Circle Expansion', description: 'Cursor expands to fill button on hover.', prompt: 'On button hover, the cursor circle expands to fill the button background.' },
  { id: 'cursor-dot-grid', title: '49. Dot Grid Reaction', description: 'Grid of dots repelling from cursor.', prompt: 'A background grid of dots that move away from the cursor.' },
  { id: 'cursor-line-tether', title: '50. Line Tether', description: 'Line connecting cursor to nearest object.', prompt: 'Draw a line from the cursor to the nearest interactive element.' },
  { id: 'cursor-color-invert', title: '51. Color Invert', description: 'Invert page colors in a radius.', prompt: 'A cursor that inverts the colors of the entire page within a circle.' },
  { id: 'cursor-emoji-trail', title: '52. Emoji Trail', description: 'Dropping emojis behind the mouse.', prompt: 'Leave a trail of random emojis behind the cursor.' },
  { id: 'cursor-video-reveal', title: '53. Video Scrub Reveal', description: 'Hover to play/reveal video.', prompt: 'Video plays only within the cursor radius.' },
  { id: 'cursor-magnetic-border', title: '54. Magnetic Border', description: 'Border moves towards cursor.', prompt: 'Button border distorts towards the cursor.' },
  { id: 'cursor-directional-arrow', title: '55. Direction Arrow', description: 'Arrow pointing in movement direction.', prompt: 'Cursor is an arrow that rotates to point where you move.' },

  // --- TYPOGRAPHY EFFECTS (56-80) ---
  { id: 'type-split', title: '56. Split Text', description: 'Staggered character animations.', prompt: PROMPTS['type-split'] },
  { id: 'type-mask', title: '57. Text Mask', description: 'Revealing text through clipping masks.', prompt: PROMPTS['type-mask'] },
  { id: 'type-stroke', title: '58. Stroke Animation', description: 'Drawing text outlines with SVG.', prompt: PROMPTS['type-stroke'] },
  { id: 'type-fill', title: '59. Liquid Fill', description: 'Text filling up like water on scroll.', prompt: PROMPTS['type-fill'] },
  { id: 'type-variable', title: '60. Variable Font', description: 'Animating font weight and width.', prompt: PROMPTS['type-variable'] },
  { id: 'type-3d', title: '61. 3D Layered', description: 'Stacked text layers with parallax.', prompt: PROMPTS['type-3d'] },
  { id: 'type-kinetic', title: '62. Kinetic Type', description: 'Chaotic, rhythmic text motion.', prompt: PROMPTS['type-kinetic'] },
  { id: 'type-typewriter', title: '63. Typewriter', description: 'Sequential character typing effect.', prompt: PROMPTS['type-typewriter'] },
  { id: 'type-distortion', title: '64. Text Glitch', description: 'Digital distortion and warp effects.', prompt: PROMPTS['type-distortion'] },
  { id: 'type-displacement', title: '65. Displacement', description: 'Fisheye menu effect on hover.', prompt: PROMPTS['type-displacement'] },
  { id: 'text-highlight-scroll', title: '66. Highlight Scroll', description: 'Highlighting text as you read.', prompt: 'Animate a highlight background behind text on scroll.' },
  { id: 'text-rotate-scroll', title: '67. Rotate Scroll', description: 'Words rotating based on scroll velocity.', prompt: 'Rotate individual words based on scroll speed.' },
  { id: 'text-spacing-breathe', title: '68. Spacing Breathe', description: 'Letter spacing expands and contracts.', prompt: 'Animate letter-spacing in a breathing rhythm.' },
  { id: 'text-border-fill', title: '69. Border Fill', description: 'Text outline fills with color.', prompt: 'Animate text-stroke to text-fill.' },
  { id: 'text-image-fill', title: '70. Image Fill', description: 'Image masked inside text.', prompt: 'Use background-clip: text with an image.' },
  { id: 'text-skew-scroll', title: '71. Skew Scroll', description: 'Italicizing text on fast scroll.', prompt: 'Skew text based on velocity.' },
  { id: 'text-blur-in', title: '72. Blur In', description: 'Text focuses from blur.', prompt: 'Animate filter: blur() to 0 on entry.' },
  { id: 'text-scramble-hover', title: '73. Scramble Hover', description: 'Random chars resolving to text.', prompt: 'Decrypt effect on hover.' },
  { id: 'text-typewriter-loop', title: '74. Typewriter Loop', description: 'Cycling through words.', prompt: 'Type, delete, type next word.' },
  { id: 'text-path-animation', title: '75. Text on Path', description: 'Text moving along a curve.', prompt: 'Animate text along an SVG path.' },
  { id: 'text-3d-fold', title: '76. 3D Fold', description: 'Text folding down like paper.', prompt: '3D rotateX reveal.' },
  { id: 'text-shadow-long', title: '77. Long Shadow', description: 'Retro long shadow effect.', prompt: 'CSS text-shadow layering.' },
  { id: 'text-neon-glow', title: '78. Neon Glow', description: 'Flickering neon sign.', prompt: 'Text shadow glow animation.' },
  { id: 'text-gradient-flow', title: '79. Gradient Flow', description: 'Moving gradient inside text.', prompt: 'Animate background-position of gradient text.' },
  { id: 'text-mirror-reflection', title: '80. Mirror Reflection', description: 'Reflected text on floor.', prompt: 'Duplicate text flipped vertically with fade.' },

  // --- LAYOUT & VISUAL TRICKS (81-95) ---
  { id: 'layout-asymmetrical', title: '81. Asymmetrical Grid', description: 'Broken grid with overlapping elements.', prompt: PROMPTS['layout-asymmetrical'] },
  { id: 'layout-broken-grid', title: '82. Broken Grid', description: 'Elements breaking container boundaries.', prompt: PROMPTS['layout-broken-grid'] },
  { id: 'layout-overlapping', title: '83. Overlapping Sections', description: 'Cards stacking on top of each other.', prompt: PROMPTS['layout-overlapping'] },
  { id: 'layout-sticky', title: '84. Sticky Element', description: 'Sidebar content that stays in view.', prompt: PROMPTS['layout-sticky'] },
  { id: 'layout-fullscreen', title: '85. Fullscreen Slides', description: 'Snap-scrolling 100vh sections.', prompt: PROMPTS['layout-fullscreen'] },
  { id: 'visual-masking', title: '86. CSS Masking', description: 'Clipping content with shapes.', prompt: PROMPTS['visual-masking'] },
  { id: 'visual-image-reveal', title: '87. Hover Reveal', description: 'Images appearing on text hover.', prompt: PROMPTS['visual-image-reveal'] },
  { id: 'visual-clip-path', title: '88. Clip Path', description: 'Geometric shape transitions.', prompt: PROMPTS['visual-clip-path'] },
  { id: 'visual-glassmorphism', title: '89. Glassmorphism', description: 'Frosted glass UI elements.', prompt: PROMPTS['visual-glassmorphism'] },
  { id: 'visual-neumorphism', title: '90. Neumorphism', description: 'Soft extruded UI shadows.', prompt: PROMPTS['visual-neumorphism'] },
  { id: 'visual-brutalist', title: '91. Neo-Brutalism', description: 'Raw, high-contrast aesthetic.', prompt: PROMPTS['visual-brutalist'] },
  { id: 'visual-cinematic', title: '92. Cinematic Dark', description: 'Movie-style lighting and atmosphere.', prompt: PROMPTS['visual-cinematic'] },
  { id: 'visual-noise', title: '93. Animated Noise', description: 'Film grain texture overlay.', prompt: PROMPTS['visual-noise'] },
  { id: 'visual-theme-switch', title: '94. Dynamic Theme', description: 'Instant style swapping with transition.', prompt: PROMPTS['visual-theme-switch'] },
  { id: 'visual-inversion', title: '95. Color Inversion', description: 'Auto-adapting colors on scroll.', prompt: PROMPTS['visual-inversion'] },

  // --- EXPERIMENTAL & SIGNATURE (96-100) ---
  { id: 'experimental-audio', title: '96. Sound Reactive', description: 'Visualizations syncing to audio signals.', prompt: PROMPTS['experimental-audio'] },
  { id: 'experimental-time', title: '97. Time Cycle', description: 'Day/Night themes based on clock.', prompt: PROMPTS['experimental-time'] },
  { id: 'experimental-ai', title: '98. Generative Art', description: 'Algorithmic visuals created on the fly.', prompt: PROMPTS['experimental-ai'] },
  { id: 'experimental-story', title: '99. Scrollytelling', description: 'Narrative driven by scroll position.', prompt: PROMPTS['experimental-story'] },
  { id: 'experimental-timeline', title: '100. Timeline', description: 'Vertical history visualization.', prompt: PROMPTS['experimental-timeline'] },

  // --- SCROLL EFFECTS II (101-120) ---
  { id: 'scroll-camera', title: '101. 3D Camera', description: 'Flying through space on scroll.', prompt: PROMPTS['scroll-camera'] },
  { id: 'scroll-assembly', title: '102. Object Assembly', description: 'Parts coming together to form a shape.', prompt: PROMPTS['scroll-assembly'] },
  { id: 'scroll-timeline-reveal', title: '103. Timeline Reveal', description: 'Drawing a path over time.', prompt: PROMPTS['scroll-timeline-reveal'] },
  { id: 'scroll-audio', title: '104. Scroll Audio', description: 'Playback speed controlled by scroll.', prompt: PROMPTS['scroll-audio'] },
  { id: 'scroll-shader', title: '105. Shader Distortion', description: 'Liquid distortion effects.', prompt: PROMPTS['scroll-shader'] },
  { id: 'scroll-freeze', title: '106. Freeze & Reveal', description: 'Sticky section with internal animation.', prompt: PROMPTS['scroll-freeze'] },
  { id: 'scroll-morph-logo', title: '107. Morphing Logo', description: 'Logo shape shifting on scroll.', prompt: PROMPTS['scroll-morph-logo'] },
  { id: 'scroll-slicing', title: '108. Page Slicing', description: 'Splitting the screen into moving strips.', prompt: PROMPTS['scroll-slicing'] },
  { id: 'scroll-depth-stack', title: '109. Depth Stacking', description: '3D tunnel card stacking.', prompt: PROMPTS['scroll-depth-stack'] },
  { id: 'scroll-zoom-world', title: '110. Zoom Out World', description: 'From macro detail to massive scale.', prompt: PROMPTS['scroll-zoom-world'] },
  { id: 'scroll-slider', title: '111. Scroll Slider', description: 'Vertical scroll drives horizontal slide.', prompt: PROMPTS['scroll-slider'] },
  { id: 'scroll-spotlight-text', title: '112. Spotlight Text', description: 'Light beam revealing text.', prompt: PROMPTS['scroll-spotlight-text'] },
  { id: 'scroll-negative-space', title: '113. Negative Space', description: 'Expanding layout gaps on scroll.', prompt: PROMPTS['scroll-negative-space'] },
  { id: 'scroll-shake', title: '114. Camera Shake', description: 'Velocity-based jitter effect.', prompt: PROMPTS['scroll-shake'] },
  { id: 'scroll-light', title: '115. Moving Light', description: 'Shadows changing direction with scroll.', prompt: PROMPTS['scroll-light'] },
  { id: 'scroll-svg-mask', title: '116. SVG Mask', description: 'Expanding shape reveal.', prompt: PROMPTS['scroll-svg-mask'] },
  { id: 'scroll-erase', title: '117. Scroll Eraser', description: 'Scrubbing away an overlay layer.', prompt: PROMPTS['scroll-erase'] },
  { id: 'scroll-gravity', title: '118. Physics Gravity', description: 'Objects falling with momentum.', prompt: PROMPTS['scroll-gravity'] },
  { id: 'scroll-fog', title: '119. Depth Fog', description: 'Atmospheric depth based on scroll.', prompt: PROMPTS['scroll-fog'] },
  { id: 'scroll-scene-switch', title: '120. Scene Switch', description: 'Instant full-screen state changes.', prompt: PROMPTS['scroll-scene-switch'] },

  // --- ADVANCED CURSOR (121-140) ---
  { id: 'cursor-physics', title: '121. Cursor Physics', description: 'Tethered ball with collision.', prompt: PROMPTS['cursor-physics'] },
  { id: 'cursor-liquid', title: '122. Liquid Cursor', description: 'Displacing UI like water.', prompt: PROMPTS['cursor-liquid'] },
  { id: 'cursor-hover-gravity', title: '123. Hover Gravity', description: 'Grid points attracted to mouse.', prompt: PROMPTS['cursor-hover-gravity'] },
  { id: 'cursor-displacement-map', title: '124. Image Warp', description: 'Displacement map texture warping.', prompt: PROMPTS['cursor-displacement-map'] },
  { id: 'cursor-spotlight-video', title: '125. Video Spotlight', description: 'Revealing video with light.', prompt: PROMPTS['cursor-spotlight-video'] },
  { id: 'cursor-sound', title: '126. Sonic Cursor', description: 'Audio feedback on movement.', prompt: PROMPTS['cursor-sound'] },
  { id: 'cursor-parallax-depth', title: '127. Mouse Parallax', description: 'Holographic 3D layer movement.', prompt: PROMPTS['cursor-parallax-depth'] },
  { id: 'cursor-speed-scale', title: '128. Speed Scale', description: 'Deforming based on velocity.', prompt: PROMPTS['cursor-speed-scale'] },
  { id: 'cursor-magnetic-text', title: '129. Magnetic Text', description: 'Characters attracted to cursor.', prompt: PROMPTS['cursor-magnetic-text'] },
  { id: 'cursor-reveal-ui', title: '130. Fog of War UI', description: 'Revealing interface on hover.', prompt: PROMPTS['cursor-reveal-ui'] },
  { id: 'cursor-shader-brush', title: '131. Shader Brush', description: 'Painting fluids with mouse.', prompt: PROMPTS['cursor-shader-brush'] },
  { id: 'cursor-trailing-particles', title: '132. Particle Trail', description: 'Complex particle system.', prompt: PROMPTS['cursor-trailing-particles'] },
  { id: 'cursor-slice', title: '133. Object Slicing', description: 'Splitting shapes on move.', prompt: PROMPTS['cursor-slice'] },
  { id: 'cursor-inertia', title: '134. Heavy Inertia', description: 'Dragging weight feel.', prompt: PROMPTS['cursor-inertia'] },
  { id: 'cursor-context-shape', title: '135. Context Shape', description: 'Morphing based on content.', prompt: PROMPTS['cursor-context-shape'] },
  { id: 'cursor-video-preview', title: '136. Video Preview', description: 'Floating thumbnails on hover.', prompt: PROMPTS['cursor-video-preview'] },
  { id: 'cursor-spotlight-text', title: '137. Text Spotlight', description: 'Illuminating dark typography.', prompt: PROMPTS['cursor-spotlight-text'] },
  { id: 'cursor-lens', title: '138. Distortion Lens', description: 'Magnifying glass effect.', prompt: PROMPTS['cursor-lens'] },
  { id: 'cursor-multi-follower', title: '139. Multi-Layer', description: 'Concentric ring followers.', prompt: PROMPTS['cursor-multi-follower'] },
  { id: 'cursor-gesture', title: '140. Gesture Control', description: 'Drawing shapes to trigger.', prompt: PROMPTS['cursor-gesture'] },

  // --- MOTION & ANIMATION (141-160) ---
  { id: 'motion-reverse', title: '141. Reverse Scroll', description: 'Animation reversing on scroll up.', prompt: PROMPTS['motion-reverse'] },
  { id: 'motion-breathing', title: '142. Breathing UI', description: 'Infinite organic pulse.', prompt: PROMPTS['motion-breathing'] },
  { id: 'motion-blur-ui', title: '143. Motion Blur UI', description: 'Directional blur on movement.', prompt: PROMPTS['motion-blur-ui'] },
  { id: 'motion-offset', title: '144. Temporal Offset', description: 'Noise-based delay ripples.', prompt: PROMPTS['motion-offset'] },
  { id: 'motion-layout-shift', title: '145. Layout Shift', description: 'Continuous grid rearrangement.', prompt: PROMPTS['motion-layout-shift'] },
  { id: 'motion-elastic', title: '146. Elastic Snap', description: 'Spring physics opening.', prompt: PROMPTS['motion-elastic'] },
  { id: 'motion-liquid-morph', title: '147. Liquid Morph', description: 'Melting section transitions.', prompt: PROMPTS['motion-liquid-morph'] },
  { id: 'motion-noise', title: '148. Noise Motion', description: 'Drifting via Perlin noise.', prompt: PROMPTS['motion-noise'] },
  { id: 'motion-hand-drawn', title: '149. Hand Drawn', description: 'Boiling frame-by-frame feel.', prompt: PROMPTS['motion-hand-drawn'] },
  { id: 'motion-minimal', title: '150. Over-Animated', description: 'Rich motion in sparse UI.', prompt: PROMPTS['motion-minimal'] },
  { id: 'motion-typo-story', title: '151. Typo Story', description: 'Words act out meanings.', prompt: PROMPTS['motion-typo-story'] },
  { id: 'motion-sync', title: '152. Music Sync', description: 'Visuals pulsing to beat.', prompt: PROMPTS['motion-sync'] },
  { id: 'motion-guide', title: '153. Attention Guide', description: 'Moving element directs eye.', prompt: PROMPTS['motion-guide'] },
  { id: 'motion-easing', title: '154. Easing Narrative', description: 'Emotional impact of curves.', prompt: PROMPTS['motion-easing'] },
  { id: 'motion-bloom', title: '155. Color Bloom', description: 'Movement leaves ink trails.', prompt: PROMPTS['motion-bloom'] },
  { id: 'motion-blur-reveal', title: '156. Blur Reveal', description: 'Focusing from heavy blur.', prompt: PROMPTS['motion-blur-reveal'] },
  { id: 'motion-afterimage', title: '157. Afterimage', description: 'Ghost trails behind objects.', prompt: PROMPTS['motion-afterimage'] },
  { id: 'motion-physics-collapse', title: '158. Physics Collapse', description: 'UI falling apart.', prompt: PROMPTS['motion-physics-collapse'] },
  { id: 'motion-time', title: '159. Time Animation', description: 'Evolving without interaction.', prompt: PROMPTS['motion-time'] },
  { id: 'motion-cut', title: '160. Cinematic Cut', description: 'Hard instant scene changes.', prompt: PROMPTS['motion-cut'] },

  // --- SCROLL INTERACTIONS III (161-170) ---
  { id: 'scroll-image-zoom-scroll', title: '161. Image Zoom Scroll', description: 'Image scales up as you scroll past.', prompt: 'Create a sticky container where an image zooms in significantly based on scroll progress.' },
  { id: 'scroll-image-fade', title: '162. Image Fade', description: 'Smooth opacity transition on scroll.', prompt: 'An image that fades from 0 to 1 opacity as it enters the viewport center.' },
  { id: 'scroll-image-rotate', title: '163. Image Rotate', description: 'Rotation linked to scroll velocity.', prompt: 'An image that spins based on how fast the user scrolls.' },
  { id: 'scroll-image-parallax', title: '164. Image Parallax', description: 'Internal image movement within container.', prompt: 'A masked container where the inner image moves slower than the scroll speed.' },
  { id: 'scroll-image-blur', title: '165. Image Blur Out', description: 'Blur increases as image leaves view.', prompt: 'Apply a blur filter that increases as the element scrolls out of the viewport.' },
  { id: 'scroll-image-grayscale', title: '166. Grayscale to Color', description: 'Color blooms as image centers.', prompt: 'An image that starts black and white and becomes colorful when centered.' },
  { id: 'scroll-image-reveal', title: '167. Slice Reveal', description: 'Image constructed from slices.', prompt: 'An image split into horizontal slices that slide together on scroll.' },
  { id: 'scroll-image-sticky', title: '168. Sticky Stack', description: 'Images stacking like playing cards.', prompt: 'Multiple images that stick to the top and stack over each other.' },
  { id: 'scroll-image-grid', title: '169. Grid Expansion', description: 'Grid items spread out on scroll.', prompt: 'A grid of images that expands its gap/spacing based on scroll position.' },
  { id: 'scroll-image-sequence', title: '170. Image Sequence', description: 'Frame-by-frame animation on scroll.', prompt: 'Scrub through a sequence of images (like a video) based on scroll progress.' },

  // --- NAVIGATION (171-180) ---
  { id: 'nav-morph', title: '171. Morphing Nav', description: 'Navigation background morphs shape.', prompt: 'A navigation bar that changes border-radius and size when scrolling.' },
  { id: 'nav-underline', title: '172. Moving Underline', description: 'Underline follows active item.', prompt: 'A sliding underline that moves to the hovered navigation item.' },
  { id: 'nav-pill', title: '173. Pill Indicator', description: 'Background pill moves behind text.', prompt: 'A pill-shaped background that slides behind the active menu item.' },
  { id: 'nav-float', title: '174. Floating Nav', description: 'Nav appears when scrolling up.', prompt: 'A header that hides on scroll down and reveals on scroll up.' },
  { id: 'nav-sidebar', title: '175. Sidebar Push', description: 'Sidebar pushes content.', prompt: 'A sidebar menu that smoothly pushes the main content area aside.' },
  { id: 'nav-mega', title: '176. Mega Menu Reveal', description: 'Full-width menu dropdown.', prompt: 'A large menu that curtain-drops from the top navigation.' },
  { id: 'nav-circle', title: '177. Circular Nav', description: 'Items arranged in a circle.', prompt: 'Navigation items distributed along a circular path.' },
  { id: 'nav-liquid', title: '178. Liquid Tab', description: 'Gooey effect between tabs.', prompt: 'SVG goo filter applied to moving tab indicator.' },
  { id: 'nav-magnetic', title: '179. Magnetic Link', description: 'Link sticks to cursor.', prompt: 'Navigation links that magnetically pull towards the mouse cursor.' },
  { id: 'nav-indicator', title: '180. Scroll Indicator', description: 'Progress bar in nav.', prompt: 'A progress bar integrated into the navigation header.' },
  { id: 'nav-hamburger', title: '181. Hamburger Morph', description: 'Fluid morphing menu.', prompt: 'A hamburger menu button that morphs into a close icon with a fluid, organic animation, revealing a fullscreen menu.' },

  // --- CARD EFFECTS (181-190) ---
  { id: 'card-flip', title: '181. 3D Flip', description: 'Card flips to show back.', prompt: 'A card that rotates 180 degrees on Y-axis to reveal content on the back.' },
  { id: 'card-hover-lift', title: '182. Hover Lift', description: 'Card lifts with shadow.', prompt: 'Card translates up and shadow increases on hover.' },
  { id: 'card-stack', title: '183. Fan Stack', description: 'Cards fan out on hover.', prompt: 'A stack of cards that rotates and spreads out like a fan on hover.' },
  { id: 'card-spread', title: '184. Horizontal Spread', description: 'Cards slide apart.', prompt: 'Overlapping cards that slide horizontally to reveal themselves on hover.' },
  { id: 'card-carousel', title: '185. 3D Carousel', description: 'Rotating carousel of cards.', prompt: 'A 3D rotating carousel of cards in perspective.' },
  { id: 'card-glare', title: '186. Holo Glare', description: 'Holographic glare effect.', prompt: 'A shiny glare gradient that moves across the card based on mouse position.' },
  { id: 'card-border-gradient', title: '187. Gradient Border', description: 'Animated gradient border.', prompt: 'A card with a moving gradient border.' },
  { id: 'card-expand', title: '188. Expand to Full', description: 'Card expands to fullscreen.', prompt: 'A card that uses layout projection to expand to full screen on click.' },
  { id: 'card-focus', title: '189. Focus Mode', description: 'Dim others on hover.', prompt: 'Hovering one card dims all other cards in the grid.' },
  { id: 'card-pattern', title: '190. Pattern Reveal', description: 'Pattern appears on hover.', prompt: 'A subtle background pattern that fades in when hovering the card.' },

  // --- BUTTON INTERACTIONS (191-200) ---
  { id: 'button-pulse', title: '191. Pulse Button', description: 'Rhythmic pulsing glow.', prompt: 'A button with a continuous pulsing shadow animation.' },
  { id: 'button-shine', title: '192. Shine Sweep', description: 'Light sweeps across button.', prompt: 'A sheen effect that slides diagonally across the button.' },
  { id: 'button-ripple-out', title: '193. Ripple Out', description: 'Ripple effect from center.', prompt: 'A ripple that expands from the center of the button on click.' },
  { id: 'button-magnetic', title: '194. Magnetic Button', description: 'Button moves with cursor.', prompt: 'The entire button translates slightly towards the cursor.' },
  { id: 'button-morph', title: '195. Morph to Circle', description: 'Button becomes a loader.', prompt: 'A rectangular button that shrinks into a circle loader on click.' },
  { id: 'button-liquid', title: '196. Liquid Fill', description: 'Fill with liquid animation.', prompt: 'Button fills up with a liquid wave animation on hover.' },
  { id: 'button-neon', title: '197. Neon Glow', description: 'Bright neon border glow.', prompt: 'A button with a strong neon text-shadow and box-shadow.' },
  { id: 'button-ghost', title: '198. Ghost Button', description: 'Transparent with border.', prompt: 'A minimal ghost button with animated border fill on hover.' },
  { id: 'button-arrow', title: '199. Arrow Slide', description: 'Arrow appears on hover.', prompt: 'An arrow icon that slides in from the left on hover.' },
  { id: 'button-loading', title: '200. Loading State', description: 'Built-in spinner.', prompt: 'Button text replaced by a spinner animation.' },

  // --- LOADERS (201-210) ---
  { id: 'loader-circle', title: '201. Circle Spinner', description: 'Standard circular loader.', prompt: 'A rotating circular border spinner.' },
  { id: 'loader-bar', title: '202. Progress Bar', description: 'Linear loading bar.', prompt: 'A horizontal progress bar that fills up.' },
  { id: 'loader-dots', title: '203. Bouncing Dots', description: 'Three dots bouncing.', prompt: 'Three dots animating up and down in sequence.' },
  { id: 'loader-text', title: '204. Text Fade', description: 'Loading text pulsing.', prompt: 'The word "LOADING" with characters fading in sequence.' },
  { id: 'loader-glitch', title: '205. Glitch Loader', description: 'Distorted loading text.', prompt: 'Loading text with random glitch offsets.' },
  { id: 'loader-svg', title: '206. SVG Path', description: 'Drawing SVG path.', prompt: 'An SVG logo outline being drawn via stroke-dasharray.' },
  { id: 'loader-mask', title: '207. Mask Reveal', description: 'Image filling a shape.', prompt: 'A logo shape filling up with water/liquid.' },
  { id: 'loader-blur', title: '208. Blur to Focus', description: 'Content blurring in.', prompt: 'Content transitioning from blur(10px) to blur(0).' },
  { id: 'loader-progress', title: '209. Percentage', description: 'Counting number.', prompt: 'A number counting up from 0% to 100%.' },
  { id: 'loader-skeleton', title: '210. Skeleton', description: 'Placeholder pulse.', prompt: 'Gray placeholder blocks with a shimmering gradient overlay.' },

  // --- FORM ELEMENTS (211-220) ---
  { id: 'form-float-label', title: '211. Floating Label', description: 'Label moves up on focus.', prompt: 'Input label that transitions to the top border on focus.' },
  { id: 'form-focus-border', title: '212. Focus Border', description: 'Border expands from center.', prompt: 'Bottom border line that expands from center on focus.' },
  { id: 'form-shake-error', title: '213. Shake Error', description: 'Input shakes on error.', prompt: 'Input field shakes horizontally when validation fails.' },
  { id: 'form-success-check', title: '214. Success Check', description: 'Checkmark appears.', prompt: 'Green checkmark animates in on valid input.' },
  { id: 'form-password-reveal', title: '215. Password Eye', description: 'Toggle password visibility.', prompt: 'Eye icon toggles input type between password and text.' },
  { id: 'form-search-expand', title: '216. Search Expand', description: 'Search bar widens.', prompt: 'Search icon expands into a text input on click.' },
  { id: 'form-radio-custom', title: '217. Custom Radio', description: 'Animated radio button.', prompt: 'Custom styled radio button with scale animation.' },
  { id: 'form-checkbox-custom', title: '218. Custom Checkbox', description: 'Animated checkmark.', prompt: 'Custom checkbox with SVG path drawing checkmark.' },
  { id: 'form-switch-ios', title: '219. iOS Switch', description: 'Toggle switch animation.', prompt: 'Toggle switch with smooth background color transition.' },
  { id: 'form-range-slider', title: '220. Range Tooltip', description: 'Value tooltip on slider.', prompt: 'Range slider with a value tooltip that follows the thumb.' },

  // --- LAYOUT & COMPOSITION EXPERIMENTAL (221–240) ---
  { id: 'layout-exp-morphing', title: '221. Fluid Layout Morphing', description: 'Layout container changes shape continuously.', prompt: 'A main content container that morphs its border-radius and aspect ratio smoothly over time.' },
  { id: 'layout-exp-scroll-speed', title: '222. Scroll Speed Response', description: 'Layout elements bounce based on scroll velocity.', prompt: 'Grid items that stretch or compress vertically depending on how fast the user scrolls.' },
  { id: 'layout-exp-broken', title: '223. Broken Container', description: 'UI box illusion of being shattered.', prompt: 'A card layout where pieces are slightly offset and rotated to look broken/glitched.' },
  { id: 'layout-exp-time', title: '224. Time-based Layout', description: 'Layout shifts based on time.', prompt: 'Elements slowly orbit or drift to new grid positions over time.' },
  { id: 'layout-exp-asymmetric', title: '225. Asymmetric Shift', description: 'Responsive but intentionally misaligned.', prompt: 'A two-column layout where the left column is significantly lower and wider than standard grids.' },
  { id: 'layout-exp-depth', title: '226. Layered Depth', description: '3D stacked planes layout.', prompt: 'Content sections stacked in Z-space, revealing depth on hover or scroll.' },
  { id: 'layout-exp-floating', title: '227. Floating Grid', description: 'Grid items float freely.', prompt: 'A grid where items gently bob up and down independently, breaking rigidity.' },
  { id: 'layout-exp-collapse', title: '228. Collapsing Narrative', description: 'Layout collapses as you read.', prompt: 'Previous sections fold up or shrink away as the user scrolls past them.' },
  { id: 'layout-exp-negative', title: '229. Expanding Negative Space', description: 'Whitespace grows dynamically.', prompt: 'Margins between elements increase drastically as the user interacts.' },
  { id: 'layout-exp-anti-grid', title: '230. Anti-Grid', description: 'Deliberate misalignment.', prompt: 'Elements placed at random-looking offsets to defy standard grid expectations.' },
  { id: 'layout-exp-proximity', title: '231. Cursor Proximity', description: 'Layout shifts away from cursor.', prompt: 'Container borders or padding shift when the mouse gets close.' },
  { id: 'layout-exp-kinetic', title: '232. Kinetic Blocks', description: 'UI blocks with physics.', prompt: 'Divs that react with a spring physics bounce when clicked or hovered.' },
  { id: 'layout-exp-spatial', title: '233. Spatial Scroll', description: 'Scroll moves in 3D space.', prompt: 'Scrolling moves the camera through a 3D arrangement of DOM elements.' },
  { id: 'layout-exp-zoom', title: '234. Zoom Switch', description: 'Zoom level changes layout mode.', prompt: 'Simulate zooming out to switch from list view to grid view.' },
  { id: 'layout-exp-swap', title: '235. Layer Swap', description: 'Z-index illusion.', prompt: 'Background elements swap to foreground on interaction.' },
  { id: 'layout-exp-elastic', title: '236. Elastic Container', description: 'Container stretches on drag.', prompt: 'A main box that acts like jelly when the window is resized or scrolled.' },
  { id: 'layout-exp-breathe', title: '237. Breathing Layout', description: 'Padding/Margin pulses.', prompt: 'The whitespace of the page expands and contracts rhythmically.' },
  { id: 'layout-exp-margins', title: '238. Floating Margins', description: 'Margins differ per row.', prompt: 'Each row of text has a different, animating left margin.' },
  { id: 'layout-exp-typography', title: '239. Typo-Driven', description: 'Text shape dictates layout.', prompt: 'Content wraps tightly around a large, central letterform.' },
  { id: 'layout-exp-fragmentation', title: '240. Layout Fragment', description: 'UI splits apart.', prompt: 'The screen splits into shards when a specific action is taken.' },

  // --- VISUAL & MOTION STRANGE (241-260) ---
  { id: 'motion-inactivity', title: '241. Motion Inactivity', description: 'Animation triggers when user stops moving.', prompt: 'Detect inactivity.' },
  { id: 'motion-scroll-hesitation', title: '242. Scroll Hesitation', description: 'UI reacts when scrolling stops mid-way.', prompt: 'Scroll velocity check.' },
  { id: 'motion-echo', title: '243. Motion Echo', description: 'Cursor leaves a fading trail of clones.', prompt: 'Trail effect.' },
  { id: 'motion-smear', title: '244. Motion Smear', description: 'Object stretches based on velocity.', prompt: 'Stretch effect.' },
  { id: 'motion-glitch-burst', title: '245. Temporal Glitch', description: 'Short random glitch bursts over time.', prompt: 'Random glitch trigger.' },
  { id: 'motion-focus-blur', title: '246. Focus Blur', description: 'Movement causes motion blur.', prompt: 'Blur based on speed.' },
  { id: 'motion-melting', title: '247. Melting UI', description: 'UI elements dissolve/melt on interaction.', prompt: 'Turbulence displacement.' },
  { id: 'motion-feedback', title: '248. Motion Feedback', description: 'Motion instead of tooltips.', prompt: 'Animation cues.' },
  { id: 'motion-vibration', title: '249. Micro Vibration', description: 'Subtle shaking on interaction.', prompt: 'Vibration animation.' },
  { id: 'motion-hierarchy', title: '250. Motion Hierarchy', description: 'Z-index and scale driven by focus.', prompt: 'Scale and lift.' },
  { id: 'motion-acceleration', title: '251. Acceleration Story', description: 'Object speeds up to tell a story.', prompt: 'Ease-in movement.' },
  { id: 'motion-decay', title: '252. Decaying Loop', description: 'Animation that loses energy.', prompt: 'Damping oscillation.' },
  { id: 'motion-parallax-stack', title: '253. Parallax Stack', description: 'Layers moving at different speeds on hover.', prompt: 'Multi-layer move.' },
  { id: 'motion-directional', title: '254. Directional Motion', description: 'UI changes based on movement direction.', prompt: 'Direction detection.' },
  { id: 'motion-reveal-speed', title: '255. Reveal Speed', description: 'Animation speed coupled to cursor speed.', prompt: 'Velocity mapped timeline.' },
  { id: 'motion-anticipation', title: '256. Anticipation', description: 'Pull back before moving forward.', prompt: 'Anticipation bezier.' },
  { id: 'motion-emotion', title: '257. Emotional Cue', description: 'Happy vs Angry motion.', prompt: 'Bounce vs Shake.' },
  { id: 'motion-inertia', title: '258. Inertia Overload', description: 'Heavy element with slow start/stop.', prompt: 'Lerp smoothing.' },
  { id: 'motion-memory', title: '259. Motion Memory', description: 'Replays user movement path.', prompt: 'Canvas replay.' },
  { id: 'motion-story', title: '260. Motion Story', description: 'Abstract shapes telling a narrative.', prompt: 'Keyframe sequence.' },

  // --- INTERACTION & UX EXPERIMENTAL (261-280) ---
  { id: 'ux-hesitation', title: '261. Mouse Hesitation', description: 'UI suggests help when you hesitate.', prompt: PROMPTS['ux-hesitation'] },
  { id: 'ux-predictive', title: '262. Predictive UI', description: 'Pre-animating likely next actions.', prompt: PROMPTS['ux-predictive'] },
  { id: 'ux-rhythm', title: '263. Rhythm Learning', description: 'Adapting to user click speed.', prompt: PROMPTS['ux-rhythm'] },
  { id: 'ux-pacing', title: '264. Emotional Pacing', description: 'Forcing slow or fast interaction.', prompt: PROMPTS['ux-pacing'] },
  { id: 'ux-scroll-rhythm', title: '265. Scroll Rhythm', description: 'Syncing animations to scroll beat.', prompt: PROMPTS['ux-scroll-rhythm'] },
  { id: 'ux-no-buttons', title: '266. No Buttons', description: 'Interaction via gestures only.', prompt: PROMPTS['ux-no-buttons'] },
  { id: 'ux-implicit', title: '267. Implicit Cues', description: 'Guiding without text labels.', prompt: PROMPTS['ux-implicit'] },
  { id: 'ux-friction', title: '268. Intentional Friction', description: 'Slowing down important choices.', prompt: PROMPTS['ux-friction'] },
  { id: 'ux-exploratory', title: '269. Exploratory', description: 'No instructions, pure discovery.', prompt: PROMPTS['ux-exploratory'] },
  { id: 'ux-resistance', title: '270. Resistive UI', description: 'Elements that push back.', prompt: PROMPTS['ux-resistance'] },
  { id: 'ux-curiosity', title: '271. Curiosity Driven', description: 'Teasing content to provoke clicks.', prompt: PROMPTS['ux-curiosity'] },
  { id: 'ux-onetime', title: '272. One-Time', description: 'Interaction that vanishes forever.', prompt: PROMPTS['ux-onetime'] },
  { id: 'ux-evolution', title: '273. Evolving UI', description: 'Changes every time you visit.', prompt: PROMPTS['ux-evolution'] },
  { id: 'ux-affordance', title: '274. Hidden Affordance', description: 'Invisible controls found by luck.', prompt: PROMPTS['ux-affordance'] },
  { id: 'ux-mystery', title: '275. Progressive Mystery', description: 'Unlocking secrets over time.', prompt: PROMPTS['ux-mystery'] },
  { id: 'ux-focus', title: '276. Attention Focus', description: 'Blurring everything but the target.', prompt: PROMPTS['ux-focus'] },
  { id: 'ux-delayed', title: '277. Delayed Gratification', description: 'Waiting for content to bloom.', prompt: PROMPTS['ux-delayed'] },
  { id: 'ux-memory', title: '278. Memory UI', description: 'Remembering where you messed up.', prompt: PROMPTS['ux-memory'] },
  { id: 'ux-surprise', title: '279. Broken Expectations', description: 'Buttons that run away.', prompt: PROMPTS['ux-surprise'] },
  { id: 'ux-storytelling', title: '280. Interaction Story', description: 'Telling tales via clicks/drags.', prompt: PROMPTS['ux-storytelling'] },

  // --- VISUAL IDENTITY & BRAND EFFECTS (281-300) ---
  { id: 'brand-morphing', title: '281. Color Morphing', description: 'Fluid brand palette transitions.', prompt: PROMPTS['brand-morphing'] },
  { id: 'brand-living-logo', title: '282. Living Logo', description: 'Logo that breathes and reacts.', prompt: PROMPTS['brand-living-logo'] },
  { id: 'brand-reactive', title: '283. Reactive Identity', description: 'Brand changes based on user.', prompt: PROMPTS['brand-reactive'] },
  { id: 'brand-reconstruct', title: '284. Logo Reconstruct', description: 'Assembling brand marks on load.', prompt: PROMPTS['brand-reconstruct'] },
  { id: 'brand-motion-lang', title: '285. Motion Language', description: 'Consistent physics for brand.', prompt: PROMPTS['brand-motion-lang'] },
  { id: 'brand-distortion', title: '286. Identity Distortion', description: 'Recognizable even when warped.', prompt: PROMPTS['brand-distortion'] },
  { id: 'brand-patterns', title: '287. Procedural Patterns', description: 'Infinite brand texture generation.', prompt: PROMPTS['brand-patterns'] },
  { id: 'brand-sound', title: '288. Sonic Identity', description: 'Visuals driven by brand audio.', prompt: PROMPTS['brand-sound'] },
  { id: 'brand-typography', title: '289. Brand Typo Motion', description: 'Custom font behavior.', prompt: PROMPTS['brand-typography'] },
  { id: 'brand-reveal', title: '290. Interactive Reveal', description: 'User must draw the logo.', prompt: PROMPTS['brand-reveal'] },
  { id: 'brand-depth', title: '291. Brand Depth', description: '2D logo in 3D space.', prompt: PROMPTS['brand-depth'] },
  { id: 'brand-negative', title: '292. Negative Space', description: 'Logo formed by emptiness.', prompt: PROMPTS['brand-negative'] },
  { id: 'brand-disintegrate', title: '293. Disintegration', description: 'Logo turning to dust.', prompt: PROMPTS['brand-disintegrate'] },
  { id: 'brand-environment', title: '294. Brand Environment', description: 'Walking inside the brand.', prompt: PROMPTS['brand-environment'] },
  { id: 'brand-time', title: '295. Time Reactive', description: 'Brand shifts with day/night.', prompt: PROMPTS['brand-time'] },
  { id: 'brand-physics', title: '296. Physics Identity', description: 'Logo subject to gravity.', prompt: PROMPTS['brand-physics'] },
  { id: 'brand-random', title: '297. Random Animation', description: 'Never the same intro twice.', prompt: PROMPTS['brand-random'] },
  { id: 'brand-exploration', title: '298. Exploration Reveal', description: 'Finding the brand values.', prompt: PROMPTS['brand-exploration'] },
  { id: 'brand-silent', title: '299. Silent Story', description: 'Pure visual brand narrative.', prompt: PROMPTS['brand-silent'] },
  { id: 'brand-experience', title: '300. Brand Experience', description: 'The website IS the brand.', prompt: PROMPTS['brand-experience'] },

  // --- NEW ARRIVALS (301-310) ---
  { id: 'scroll-3d-grid', title: '301. 3D Grid Travel', description: 'Traveling through an infinite retro 3D grid.', prompt: 'Create a retro vaporwave style 3D grid tunnel that moves towards the camera on scroll.' },
  { id: 'scroll-parallax-zoom', title: '302. Parallax Zoom', description: 'Zooming into layers of an image with depth.', prompt: 'Implement a multi-layer photo zoom effect where the foreground expands faster than the background.' },
  { id: 'cursor-magnetic-links', title: '303. Magnetic Links', description: 'Links that snap to the cursor with elastic physics.', prompt: 'Create navigation links that magnetically snap to the cursor position with a spring animation.' },
  { id: 'text-neon-flicker', title: '304. Neon Flicker', description: 'Realistic neon sign flickering text effect.', prompt: 'Simulate a broken neon sign with randomized flickering intensity and glow effects.' },
  { id: 'visual-glitch-image', title: '305. Image Glitch', description: 'RGB split and displacement glitch on hover.', prompt: 'Apply an RGB split and horizontal slice distortion to an image on mouse hover.' },
  { id: 'motion-path-follow', title: '306. Path Follow', description: 'Object following a complex SVG path on scroll.', prompt: 'Animate a small object (like a car or dot) following a curved SVG path based on scroll percentage.' },
  { id: 'three-particle-terrain', title: '307. Particle Terrain', description: '3D terrain generated from particles.', prompt: 'Generate a 3D terrain map using thousands of particles that undulate like waves.' },
  { id: 'brand-logo-morph', title: '308. Logo Morph', description: 'Smooth SVG path morphing between icons.', prompt: 'Morph a simple circle icon into a square, then a triangle, using SVG path interpolation.' },
  { id: 'ux-micro-interaction', title: '309. Micro Like', description: 'Satisfying "Like" button animation with particles.', prompt: 'Create a Twitter-like heart animation with exploding colorful particles upon clicking.' },
  { id: 'experimental-noise-field', title: '310. Noise Field', description: 'Interactive Perlin noise flow field.', prompt: 'Visualize a flow field using Perlin noise where particles trail and follow invisible vectors.' },

  // --- 🧩 XVI. MICRO-INTERACTIONS (311–330) ---
  { id: 'micro-toggle-elastic', title: '311. Elastic Toggle', description: 'Switch with jelly-like bounce.', prompt: 'Create a toggle switch that stretches and bounces like jelly when clicked.' },
  { id: 'micro-button-morph-loader', title: '312. Button Morph Loader', description: 'Button transforms into spinner.', prompt: 'A button that shrinks into a circular loader on click.' },
  { id: 'micro-checkbox-particle', title: '313. Particle Checkbox', description: 'Explosion of confetti on check.', prompt: 'Checking a box triggers a micro-explosion of particles.' },
  { id: 'micro-slider-fluid', title: '314. Fluid Slider', description: 'Slider thumb morphs shape.', prompt: 'A range slider where the thumb bubble deforms based on drag speed.' },
  { id: 'micro-input-shake', title: '315. Validation Shake', description: 'Input shakes on error.', prompt: 'Micro-shake animation for invalid input fields.' },
  { id: 'micro-card-tilt-glare', title: '316. 3D Card Glare', description: 'Holo glare on hover.', prompt: 'A card that tilts 3D with a shiny glare layer moving opposite to mouse.' },
  { id: 'micro-icon-morph', title: '317. Icon Morphing', description: 'Menu to Close icon morph.', prompt: 'Smooth SVG path transition between hamburger menu and X icon.' },
  { id: 'micro-nav-underline', title: '318. Magnetic Underline', description: 'Nav line snaps to active item.', prompt: 'A sliding underline that uses spring physics to snap to hovered items.' },
  { id: 'micro-tooltip-follow', title: '319. Liquid Tooltip', description: 'Tooltip trailing cursor.', prompt: 'A tooltip that follows the mouse with a fluid lag effect.' },
  { id: 'micro-fab-expand', title: '320. FAB Expansion', description: 'Floating button speed dial.', prompt: 'A floating action button that spirals out sub-actions.' },
  { id: 'micro-like-heart', title: '321. Twitter Like', description: 'Heart animation with bubbles.', prompt: 'Heart icon that pops and emits circles on click.' },
  { id: 'micro-delete-shred', title: '322. Shredder Delete', description: 'Item gets shredded.', prompt: 'List item animation that looks like it goes through a paper shredder.' },
  { id: 'micro-drag-snap', title: '323. Drag & Snap', description: 'Element snaps to grid.', prompt: 'Draggable element with heavy magnetic snap points.' },
  { id: 'micro-pull-refresh', title: '324. Pull Refresh', description: 'Elastic pull down.', prompt: 'Pull to refresh animation with liquid resistance.' },
  { id: 'micro-tab-slide', title: '325. Sliding Tab', description: 'Background pill slide.', prompt: 'Tabs where the active background slides smoothly between items.' },
  { id: 'micro-scroll-progress', title: '326. Circular Progress', description: 'Reading progress ring.', prompt: 'Fixed circle that fills up as you scroll down.' },
  { id: 'micro-accordion-spring', title: '327. Spring Accordion', description: 'Bouncy expansion.', prompt: 'Accordion item that opens with an overshoot spring animation.' },
  { id: 'micro-radio-wave', title: '328. Radio Wave', description: 'Ripple on selection.', prompt: 'Radio button that emits a ripple wave when selected.' },
  { id: 'micro-text-highlight', title: '329. Marker Highlight', description: 'Realistic marker draw.', prompt: 'Text highlight that looks like a hand-drawn marker stroke.' },
  { id: 'micro-bell-shake', title: '330. Notification Bell', description: 'Ring animation.', prompt: 'Bell icon that rings physically when a notification arrives.' },

  // --- 📊 XVII. DATA VISUALIZATION (331–350) ---
  { id: 'data-bar-race', title: '331. Bar Chart Race', description: 'Bars overtaking each other.', prompt: 'Animated bar chart where bars swap positions based on values.' },
  { id: 'data-pie-drill', title: '332. Drill-down Pie', description: 'Pie slice expands to new chart.', prompt: 'Clicking a pie slice zooms into it to reveal a sub-chart.' },
  { id: 'data-line-draw', title: '333. Line Path Draw', description: 'Graph drawing itself.', prompt: 'SVG line graph that animates the stroke dashoffset.' },
  { id: 'data-scatter-gravity', title: '334. Gravity Scatter', description: 'Points falling into place.', prompt: 'Scatter plot points falling from top with physics.' },
  { id: 'data-radar-scan', title: '335. Radar Scanner', description: 'Scanning sweep effect.', prompt: 'Circular radar chart with a rotating scan beam.' },
  { id: 'data-heatmap-glow', title: '336. Glowing Heatmap', description: 'Pulsing intensity spots.', prompt: 'Heatmap grid where hot spots pulse with neon glow.' },
  { id: 'data-network-force', title: '337. Force Graph', description: 'Nodes repelling/attracting.', prompt: 'Network graph simulation with D3-like physics.' },
  { id: 'data-globe-spin', title: '338. Data Globe', description: '3D spinning earth with points.', prompt: 'Wireframe globe with data points mapped to lat/long.' },
  { id: 'data-stream-flow', title: '339. Data Stream', description: 'Matrix code rain style data.', prompt: 'Numbers cascading down columns like The Matrix.' },
  { id: 'data-donut-progress', title: '340. Donut Fill', description: 'Circular stats filling up.', prompt: 'Multiple concentric donut charts animating to values.' },
  { id: 'data-candlestick', title: '341. Live Candles', description: 'Stock market ticker.', prompt: 'Candlestick chart updating in real-time with color flashes.' },
  { id: 'data-area-wave', title: '342. Wave Area', description: 'Smooth sine wave chart.', prompt: 'Area chart that undulates like a liquid wave.' },
  { id: 'data-bubble-pack', title: '343. Bubble Pack', description: 'Circles packing together.', prompt: 'Bubble chart where circles collide and pack efficiently.' },
  { id: 'data-sankey-flow', title: '344. Particle Sankey', description: 'Particles flowing along paths.', prompt: 'Sankey diagram with particles traveling the links.' },
  { id: 'data-voronoi-hover', title: '345. Voronoi Cells', description: 'Dynamic cell hovering.', prompt: 'Voronoi diagram where cells expand on hover.' },
  { id: 'data-tree-grow', title: '346. Fractal Tree', description: 'Recursive branching.', prompt: 'Tree graph growing branches recursively.' },
  { id: 'data-histogram-beat', title: '347. Audio Histogram', description: 'Bars reacting to audio.', prompt: 'Histogram bars bouncing to a beat.' },
  { id: 'data-gauge-needle', title: '348. Elastic Gauge', description: 'Needle wobble.', prompt: 'Speedometer gauge with a needle that overshoots.' },
  { id: 'data-realtime-graph', title: '349. Realtime Pulse', description: 'Heartbeat monitor.', prompt: 'ECG style line graph scrolling horizontally.' },
  { id: 'data-particles-globe', title: '350. Particle Globe', description: 'Dots forming a sphere.', prompt: '3D point cloud arranged in a sphere shape.' },

  // --- 👾 XVIII. CYBERPUNK & GLITCH (351–370) ---
  { id: 'cyber-glitch-text', title: '351. RGB Split Text', description: 'Chromatic aberration.', prompt: 'Text with red/blue channels offsetting randomly.' },
  { id: 'cyber-hologram', title: '352. Hologram Card', description: 'Flickering projection.', prompt: 'Card with scanlines and transparency flicker.' },
  { id: 'cyber-scanlines', title: '353. CRT Monitor', description: 'Old screen effect.', prompt: 'Overlay with rolling scanlines and curvature.' },
  { id: 'cyber-vhs-tracking', title: '354. VHS Tracking', description: 'Tape distortion.', prompt: 'Screen distortion waving up the screen.' },
  { id: 'cyber-pixel-sort', title: '355. Pixel Sort', description: 'Melting pixels.', prompt: 'Image pixels sorted vertically on hover.' },
  { id: 'cyber-neon-flicker', title: '356. Broken Neon', description: 'Buzzing light.', prompt: 'Neon sign that flickers and buzzes.' },
  { id: 'cyber-matrix-rain', title: '357. Digital Rain', description: 'Code falling.', prompt: 'Green code characters falling down black screen.' },
  { id: 'cyber-data-mosh', title: '358. Datamosh', description: 'Video compression artifact.', prompt: 'Image transition creating dragging pixel artifacts.' },
  { id: 'cyber-hud-ui', title: '359. Sci-Fi HUD', description: 'Iron Man interface.', prompt: 'Spinning rings and data readouts overlay.' },
  { id: 'cyber-terminal', title: '360. Retro Terminal', description: 'Command line typing.', prompt: 'Green text on black typing out commands.' },
  { id: 'cyber-distortion-field', title: '361. Distortion Field', description: 'Warping space.', prompt: 'Radial distortion filter following mouse.' },
  { id: 'cyber-circuit-board', title: '362. Circuit Flow', description: 'Electrons moving.', prompt: 'Lines animating like electricity on a circuit.' },
  { id: 'cyber-noise-grain', title: '363. Static Noise', description: 'TV static.', prompt: 'Animated white noise canvas overlay.' },
  { id: 'cyber-slice-transition', title: '364. Slice Transition', description: 'Screen cutting.', prompt: 'Screen splits diagonally during transition.' },
  { id: 'cyber-warp-speed', title: '365. Star Jump', description: 'Lines streaking past.', prompt: 'Stars stretching into lines moving forward.' },
  { id: 'cyber-low-poly', title: '366. Low Poly Grid', description: 'Wireframe terrain.', prompt: 'Moving wireframe landscape grid.' },
  { id: 'cyber-ascii-art', title: '367. ASCII Video', description: 'Video rendered as text.', prompt: 'Convert pixels to ASCII characters in real-time.' },
  { id: 'cyber-chromatic-zoom', title: '368. Chromatic Zoom', description: 'RGB split on zoom.', prompt: 'Zooming in splits colors at edges.' },
  { id: 'cyber-liquid-metal', title: '369. Liquid Metal', description: 'Chrome reflection.', prompt: 'Shiny metallic surface rippling.' },
  { id: 'cyber-laser-scan', title: '370. Laser Scan', description: 'Red beam scanning.', prompt: 'Laser line passing over object revealing wireframe.' },

  // --- 🌿 XIX. NATURE & PHYSICS (371–390) ---
  { id: 'nature-rain-window', title: '371. Rain on Window', description: 'Droplets running down.', prompt: 'Simulation of raindrops sliding down glass.' },
  { id: 'nature-snow-fall', title: '372. Gentle Snow', description: 'Drifting snowflakes.', prompt: 'Snowflakes falling with turbulence and sway.' },
  { id: 'nature-water-ripple', title: '373. Pond Ripple', description: 'Interactive water.', prompt: 'Mouse creates ripples in water surface.' },
  { id: 'nature-leaves-wind', title: '374. Falling Leaves', description: 'Leaves swirling.', prompt: 'Autumn leaves blowing in wind.' },
  { id: 'nature-fire-flame', title: '375. Procedural Fire', description: 'Rising flames.', prompt: 'Particle system simulating fire.' },
  { id: 'nature-smoke-plume', title: '376. Smoke Trail', description: 'Wispy smoke.', prompt: 'Smoke rising and diffusing.' },
  { id: 'nature-cloth-sim', title: '377. Cloth Physics', description: 'Waving fabric.', prompt: 'Grid of points connected by springs (cloth).' },
  { id: 'nature-gravity-balls', title: '378. Bouncing Balls', description: 'Physics collision.', prompt: 'Balls bouncing and colliding with gravity.' },
  { id: 'nature-confetti', title: '379. Confetti Cannon', description: 'Paper explosion.', prompt: 'Confetti particles blasting out.' },
  { id: 'nature-starfield', title: '380. Star Field', description: 'Twinkling night sky.', prompt: 'Stars twinkling and shooting stars.' },
  { id: 'nature-fog-roll', title: '381. Rolling Fog', description: 'Mist passing by.', prompt: 'Perlin noise clouds moving horizontally.' },
  { id: 'nature-sun-rays', title: '382. God Rays', description: 'Light shafts.', prompt: 'Volumetric light rays shining through clouds.' },
  { id: 'nature-grass-sway', title: '383. Grass Field', description: 'Wind in grass.', prompt: 'Blades of grass bending with noise wind.' },
  { id: 'nature-jellyfish', title: '384. Deep Sea Jelly', description: 'Floating organic movement.', prompt: 'Tentacles moving fluidly underwater.' },
  { id: 'nature-galaxy-spiral', title: '385. Galaxy Spiral', description: 'Rotating stars.', prompt: 'Particles arranged in spiral galaxy arms.' },
  { id: 'nature-lightning', title: '386. Lightning Bolt', description: 'Electric arc.', prompt: 'Recursive fractal lightning strike.' },
  { id: 'nature-bubble-rise', title: '387. Champagne Bubbles', description: 'Rising carbonation.', prompt: 'Tiny bubbles rising fast in liquid.' },
  { id: 'nature-ink-water', title: '388. Ink in Water', description: 'Fluid diffusion.', prompt: 'Ink drop expanding organically in water.' },
  { id: 'nature-sand-grain', title: '389. Falling Sand', description: 'Cellular automata.', prompt: 'Sand grains stacking (like powder game).' },
  { id: 'nature-flock-birds', title: '390. Bird Flocking', description: 'Boids algorithm.', prompt: 'Triangle boids flying together.' },

  // --- 🅰️ XX. ADVANCED TYPOGRAPHY II (391–410) ---
  { id: 'type-adv-kinetic-loop', title: '391. Kinetic Loop', description: 'Words circling.', prompt: 'Text rotating in a 3D cylinder loop.' },
  { id: 'type-adv-path-follow', title: '392. Path Follow', description: 'Snake text.', prompt: 'Text string slithering along a curve.' },
  { id: 'type-adv-elastic-stretch', title: '393. Elastic Stretch', description: 'Pulling letters.', prompt: 'Letters stretching like rubber on drag.' },
  { id: 'type-adv-shatter', title: '394. Text Shatter', description: 'Breaking glass.', prompt: 'Text breaking into shards on click.' },
  { id: 'type-adv-liquid-melt', title: '395. Type Melt', description: 'Dripping font.', prompt: 'Font melting downwards like wax.' },
  { id: 'type-adv-neon-sign', title: '396. Neon Sign', description: 'Realistic glow.', prompt: 'Text with glass tube stroke and glow.' },
  { id: 'type-adv-emboss-gold', title: '397. Gold Emboss', description: 'Metallic shader.', prompt: 'Shiny gold texture on 3D extruded text.' },
  { id: 'type-adv-retro-stack', title: '398. Retro Stack', description: 'Repeated layers.', prompt: '80s style stacked text layers.' },
  { id: 'type-adv-variable-breathe', title: '399. Variable Breathe', description: 'Weight pulse.', prompt: 'Font weight oscillating smoothly.' },
  { id: 'type-adv-slit-scan', title: '400. Slit Scan', description: 'Time displacement.', prompt: 'Text stretched by slit scan effect.' },
  { id: 'type-adv-ascii-transform', title: '401. ASCII Morph', description: 'Chars changing.', prompt: 'Text transforming via random characters.' },
  { id: 'type-adv-smoke-fade', title: '402. Smoke Fade', description: 'Evaporating words.', prompt: 'Text turning into smoke particles.' },
  { id: 'type-adv-wave-flag', title: '403. Flag Wave Text', description: 'Rippling sine.', prompt: 'Text waving like a flag.' },
  { id: 'type-adv-spotlight-mask', title: '404. Spotlight Mask', description: 'Light beam.', prompt: 'Text visible only inside spotlight.' },
  { id: 'type-adv-isometric-block', title: '405. Isometric Block', description: '3D Extrusion.', prompt: 'Long isometric shadow extrusion.' },
  { id: 'type-adv-texture-clip', title: '406. Video Texture', description: 'Video inside text.', prompt: 'Text masking a playing video.' },
  { id: 'type-adv-flip-card', title: '407. Flip Letter', description: 'Airport board.', prompt: 'Split-flap display animation per letter.' },
  { id: 'type-adv-write-on', title: '408. Write On', description: 'Handwriting.', prompt: 'SVG stroke path animating like handwriting.' },
  { id: 'type-adv-glitch-snap', title: '409. Glitch Snap', description: 'RGB Offset.', prompt: 'Text snapping into place with glitch.' },
  { id: 'type-adv-mirror-floor', title: '410. Floor Reflection', description: 'Wet floor.', prompt: 'Text with gradient fade reflection below.' },
];
